name:                groupby
version:             0.1.0.0
dependencies:
- base >= 4.7 && < 5
- optparse-applicative
- conduit
- csv-conduit
- conduit-algorithms
- text
- temporary
- directory
- filepath
- transformers
- containers

ghc-options:
- -O2
- -fno-full-laziness
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  groupby-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - groupby
    when:
      - condition: false
        other-modules: Paths_groupby

tests:
  groupby-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - groupby
    - hspec
