name: build
on: [push]
jobs:
  build:
    name: groupby:exe:groupby-exe
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.4.7'
          cabal-version: 'latest'
          enable-stack: true
          stack-version: 'latest'
      - run: |
          stack build
          echo "artifactPath=$(stack path --local-install-root)/bin/*" >> $GITHUB_ENV
      - run: stack test
      - uses: actions/upload-artifact@v3
        with:
          name: groupby-exe
          path: ${{ env.artifactPath }}
          if-no-files-found: error
      - run: stack clean --full
