on: [push]
name: build
jobs:
  build:
    name: groupby:exe:groupby-exe
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.4.7'
          cabal-version: 'latest'
          enable-stack: true
          stack-version: 'latest'
      - run: stack build
      - run: stack test
